# Generated by Django 4.2.7 on 2025-10-21 22:42

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Официальный сайт')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Метка')),
                ('original_number', models.CharField(blank=True, max_length=50, verbose_name='Оригинальный номер')),
                ('manufacturer_number', models.CharField(blank=True, max_length=50, verbose_name='Номер производителя')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общее количество')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='На складе')),
                ('reserve', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='В резерве')),
                ('available', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступно')),
                ('price_opt', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оптовая цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Автозапчасть',
                'verbose_name_plural': 'Автозапчасти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('address', models.TextField(verbose_name='Адрес склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.part_image_upload_path, verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.part', verbose_name='Автозапчасть')),
            ],
            options={
                'verbose_name': 'Изображение автозапчасти',
                'verbose_name_plural': 'Изображения автозапчастей',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_par_brand_i_e913f7_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['warehouse', 'is_active'], name='catalog_par_warehou_cc712c_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['price_opt'], name='catalog_par_price_o_0607b0_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['available'], name='catalog_par_availab_43e9af_idx'),
        ),
    ]
