# Generated by Django 4.2.7 on 2025-11-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_order', models.BooleanField(default=True, verbose_name='Email при новом заказе')),
                ('email_low_stock', models.BooleanField(default=True, verbose_name='Email при низком остатке')),
                ('push_new_order', models.BooleanField(default=True, verbose_name='Push при новом заказе')),
                ('push_low_stock', models.BooleanField(default=False, verbose_name='Push при низком остатке')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Звуковые уведомления')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', 'Новый заказ'), ('low_stock', 'Низкий остаток'), ('zero_stock', 'Нулевой остаток'), ('stuck_order', 'Заказ застрял'), ('system', 'Системное')], max_length=20, verbose_name='Тип уведомления')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sent_email', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('related_order_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанного заказа')),
                ('related_part_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанного товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx')],
            },
        ),
    ]
