# Generated by Django 4.2.7 on 2025-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(help_text='Уникальный номер заказа', max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
    ]
