# Generated by Django 4.2.7 on 2025-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('packed', 'Собран'), ('ready_for_shipment', 'Готов к отправке'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('arrived', 'Прибыл в город'), ('out_for_delivery', 'Передан в доставку'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('returned', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('packed', 'Собран'), ('ready_for_shipment', 'Готов к отправке'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('arrived', 'Прибыл в город'), ('out_for_delivery', 'Передан в доставку'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('returned', 'Возвращён')], max_length=20, verbose_name='Статус'),
        ),
    ]
