# Generated by Django 4.2.7 on 2025-10-21 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Уникальный идентификатор страницы (например: 'home', 'catalog', 'about')", unique=True, verbose_name='URL страницы')),
                ('title', models.CharField(help_text='Заголовок страницы (до 60 символов)', max_length=60, verbose_name='Title')),
                ('description', models.TextField(help_text='Описание страницы (до 160 символов)', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='Description')),
                ('keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Заголовок для социальных сетей', max_length=60, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Изображение для социальных сетей (1200x630px)', null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('og_image_url', models.URLField(blank=True, help_text='Внешний URL изображения для социальных сетей', null=True, verbose_name='OG Image URL')),
                ('canonical_url', models.URLField(blank=True, help_text='Канонический URL страницы', null=True, verbose_name='Canonical URL')),
                ('robots', models.CharField(default='index, follow', help_text='Директивы для поисковых роботов', max_length=100, verbose_name='Robots')),
                ('yandex_verification', models.CharField(blank=True, help_text='Код подтверждения Яндекс.Вебмастер', max_length=100, verbose_name='Yandex Verification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SEO страница',
                'verbose_name_plural': 'SEO страницы',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GoodDrive', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(default='Интернет-магазин автозапчастей GoodDrive', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='Описание сайта')),
                ('default_og_image', models.ImageField(blank=True, help_text='Изображение по умолчанию для социальных сетей', null=True, upload_to='seo/default/', verbose_name='Изображение по умолчанию для OG')),
                ('yandex_verification', models.CharField(blank=True, help_text='Код подтверждения Яндекс.Вебмастер', max_length=100, verbose_name='Yandex Verification')),
                ('google_verification', models.CharField(blank=True, help_text='Код подтверждения Google Search Console', max_length=100, verbose_name='Google Verification')),
                ('yandex_metrica', models.CharField(blank=True, help_text='ID счетчика Яндекс.Метрики', max_length=20, verbose_name='Yandex Metrica ID')),
                ('google_analytics', models.CharField(blank=True, help_text='ID счетчика Google Analytics', max_length=20, verbose_name='Google Analytics ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SEO настройки',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
    ]
